INSERT INTO oxn711nfcpjgwcr2.review
(
    review,
    rating,
    created_at,
    user_id,
    product_id,
)
VALUES
(
    'An electric guitar is a guitar that uses one or more pickups to convert the vibration of its strings into electrical signals. The vibration occurs when a guitar player strums, plucks, fingerpicks, slaps or taps the strings. The pickup generally uses electromagnetic induction to create this signal, which being relatively weak is fed into a guitar amplifier before being sent to the speaker(s), which converts it into audible sound.',
    3,
    3,
    10
);

insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 5, '2019-09-28T11:28:17Z', 16, 21);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 2, '2019-10-10T08:12:58Z', 16, 2);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 5, '2019-04-25T03:59:20Z', 17, 18);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 0, '2019-10-07T17:08:20Z', 14, 22);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 2, '2019-07-20T02:14:48Z', 10, 17);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 3, '2019-03-22T13:08:39Z', 14, 18);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 5, '2019-03-06T12:46:54Z', 14, 6);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2019-08-25T18:40:36Z', 13, 9);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 4, '2019-04-25T10:48:44Z', 10, 19);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 4, '2018-12-16T20:38:06Z', 17, 11);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 5, '2019-04-18T14:03:46Z', 11, 7);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 5, '2019-09-18T12:57:08Z', 17, 16);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 2, '2019-07-14T22:06:39Z', 11, 24);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 5, '2019-11-15T22:46:39Z', 13, 10);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2019-04-17T17:39:44Z', 11, 22);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 4, '2019-06-14T20:48:43Z', 13, 6);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Sed ante. Vivamus tortor. Duis mattis egestas metus.', 2, '2019-10-28T21:12:55Z', 12, 16);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 2, '2018-12-03T08:13:39Z', 12, 18);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 0, '2019-01-06T06:56:33Z', 11, 17);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Fusce consequat. Nulla nisl. Nunc nisl.', 1, '2019-05-14T01:00:43Z', 13, 1);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Fusce consequat. Nulla nisl. Nunc nisl.', 3, '2019-10-31T20:29:24Z', 11, 7);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 0, '2018-12-08T08:15:59Z', 16, 10);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 0, '2019-03-23T17:21:03Z', 17, 19);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 2, '2019-11-13T12:22:40Z', 14, 18);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 4, '2019-11-06T09:39:49Z', 16, 8);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, '2018-12-08T03:08:52Z', 9, 6);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 3, '2019-09-24T03:02:08Z', 12, 19);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 5, '2019-07-11T20:46:13Z', 15, 19);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Fusce consequat. Nulla nisl. Nunc nisl.', 2, '2019-03-18T16:57:46Z', 16, 17);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 2, '2019-08-03T01:58:27Z', 10, 24);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 3, '2019-06-08T08:06:20Z', 15, 21);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 2, '2019-04-30T17:03:13Z', 13, 2);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 3, '2019-11-23T07:46:56Z', 10, 21);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Sed ante. Vivamus tortor. Duis mattis egestas metus.', 0, '2019-10-29T17:15:59Z', 12, 23);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Fusce consequat. Nulla nisl. Nunc nisl.', 0, '2019-07-14T06:14:38Z', 16, 19);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 0, '2019-11-06T17:42:33Z', 12, 6);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 5, '2019-10-27T04:40:26Z', 12, 11);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1, '2019-05-07T14:35:35Z', 16, 20);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2018-12-11T14:46:09Z', 12, 3);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 3, '2019-03-04T10:32:26Z', 12, 24);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 4, '2019-07-27T11:54:13Z', 17, 16);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2019-05-23T15:01:04Z', 17, 9);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1, '2019-08-31T16:53:31Z', 12, 16);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 5, '2019-03-10T00:15:45Z', 12, 10);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 0, '2019-01-31T02:23:08Z', 15, 3);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 5, '2019-07-22T18:11:27Z', 16, 9);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2018-12-27T08:36:13Z', 9, 18);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 0, '2018-12-14T17:45:13Z', 11, 22);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 5, '2019-02-19T05:12:02Z', 12, 8);
insert into oxn711nfcpjgwcr2.review (review, rating, created_at, user_id, product_id) values ('Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 1, '2019-05-25T08:13:59Z', 13, 11);
